# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 06:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField()),
                ('phone', models.CharField(max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('location', models.CharField(max_length=10)),
                ('combination', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('task_description', models.TextField()),
                ('handout_type', models.TextField()),
                ('location', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('class_name', models.CharField(max_length=10)),
                ('locker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shift.Locker')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.Employee')),
            ],
        ),
    ]
