# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_auto_20171122_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
