# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0005_auto_20171122_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='marketer_works',
            new_name='marketers',
        ),
    ]
