# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0006_auto_20171122_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='lead_marketer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lead_marketer', to='shift.Marketer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='marketers',
            field=models.ManyToManyField(related_name='marketers', to='shift.Marketer'),
        ),
    ]
