# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0007_auto_20171123_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='handout_type',
            field=models.CharField(max_length=20),
        ),
    ]
