# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0008_auto_20171123_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='task_description',
        ),
    ]
