# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0010_auto_20171123_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.Locker'),
        ),
    ]
