# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0013_auto_20171123_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.Manager'),
        ),
    ]
