# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0014_auto_20171123_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='lead_marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_marketer', to='shift.Marketer'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='marketers',
            field=models.ManyToManyField(blank=True, null=True, related_name='marketers', to='shift.Marketer'),
        ),
    ]
