# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0015_auto_20171123_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='max_marketers',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='marketers',
            field=models.ManyToManyField(blank=True, related_name='marketers', to='shift.Marketer'),
        ),
    ]
