# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0016_auto_20171201_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='max_marketers',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
